add instant update of language title
Geovation/flutter_sandbox pull request #115
Opened 2021-05-13 15:35 UTC by mysticeti

2021-05-13 16:32 UTC, joykuotw requested changes

2021-05-13 16:32 UTC, joykuotw commented on lib/home_page.dart
> +
The app bar title will be set to languages page title on every page which is incorrect.

2021-05-14 05:41 UTC, mysticeti commented on lib/home_page.dart
> +
Sorry for the mistake. It has been fixed in the next commit.

2021-05-14 09:53 UTC, merged

2021-05-14 09:53 UTC, joykuotw commented
Merged, tho It would be better to have the provider for all titles, not just for the languages page. I will make the update later.