Add sqlite with moor
Geovation/flutter_sandbox pull request #153
Opened 2021-06-29 14:47 UTC by mysticeti

2021-06-29 23:32 UTC, joykuotw requested changes

2021-06-29 23:32 UTC, joykuotw commented on lib/database/database_page.dart
> +    }
addDataSembast and addDataMoor are called all the time. As you can see, moor keeps querying which should be avoided.
<img width="1102" alt="Screenshot 2021-06-30 at 00 18 50" src="https://user-images.githubusercontent.com/25618204/123879608-1f836480-d939-11eb-90f9-3e4fc5c3d10f.png">

2021-06-29 23:32 UTC, joykuotw commented on lib/database/database_page.dart
> +    _setActiveTabIndex();
why call `_setActiveTabIndex()` again?

2021-06-30 09:19 UTC, mysticeti commented on lib/database/database_page.dart
> +    _setActiveTabIndex();
To initialize the FAB onPressed function. In the beginning it is an empty function

2021-07-02 11:04 UTC, joykuotw approved these changes

2021-07-02 11:04 UTC, merged

2021-07-02 11:04 UTC, joykuotw commented
not necessary to use consumer as there is already provider.of available.
Merge this for now and I will update it in the next commit.