add_shared_pref for dark mode
Geovation/flutter_sandbox pull request #166
Opened 2021-07-20 14:39 UTC by mysticeti

2021-07-21 17:31 UTC, joykuotw requested changes

2021-07-21 17:31 UTC, joykuotw commented on lib/app_settings.dart
> +    }
Why need `isFirstRun`? there is no difference.

2021-07-21 17:31 UTC, joykuotw commented on lib/main.dart
> +  bool isFirstRun = true;
not used.

2021-07-22 08:33 UTC, mysticeti commented on lib/app_settings.dart
> +    }
Removed it. It does not do anything

2021-07-22 08:34 UTC, mysticeti commented on lib/main.dart
> +  bool isFirstRun = true;
Removed in the next commit. Thank you for pointing it out.

2021-07-26 22:55 UTC, joykuotw approved these changes

2021-07-26 22:56 UTC, merged