add http rest api mock call
Geovation/flutter_sandbox pull request #167
Opened 2021-08-02 15:38 UTC by mysticeti

issue: to look into flutterLocalNotificationsPlugin seems to be null in main.dart.

2021-08-02 23:14 UTC, joykuotw requested changes

2021-08-04 08:55 UTC, mysticeti commented on lib/rest_api/rest_api_page.dart
> +        : deviceData.size.width * 0.8;
Removed the unused variables in the next commit

2021-08-04 08:55 UTC, mysticeti commented on lib/rest_api/rest_api_page.dart
> +      );
Removed the autoclose option.

2021-08-04 23:05 UTC, joykuotw approved these changes

2021-08-04 23:09 UTC, merged