add face detection
Geovation/flutter_sandbox pull request #171
Opened 2021-08-25 17:14 UTC by mysticeti

2021-08-31 10:52 UTC, joykuotw requested changes
Not able to open?
![Screenshot_1630407071](https://user-images.githubusercontent.com/25618204/131490075-20b18de7-acbd-4c86-86b5-daaf4df1a55d.png)

2021-08-31 10:52 UTC, joykuotw commented on lib/google_ml_kit/camera_view.dart
> +    print(widget.cameras.length);
is this needed?

2021-08-31 13:17 UTC, mysticeti commented on lib/google_ml_kit/camera_view.dart
> +    print(widget.cameras.length);
removed this statement in the next commit.

2021-08-31 13:17 UTC, mysticeti commented
bug fix in the next commit. Thank you for pointing it out.

2021-08-31 17:36 UTC, joykuotw requested changes
not working on my side, even the bar code scanner is not working either now. You might have to show me a demo.

There is also an error while switching the camera
![Screenshot_1630431266](https://user-images.githubusercontent.com/25618204/131549536-541010e7-a467-4736-b231-bd24f4212d04.png)

2021-08-31 17:36 UTC, joykuotw commented on lib/google_ml_kit/google_ml_kit_page.dart
> +        //   );
why leave this?

2021-09-01 10:59 UTC, mysticeti commented on lib/google_ml_kit/google_ml_kit_page.dart
> +        //   );
Removed the commented out code

2021-09-01 11:01 UTC, mysticeti commented
The camera switching had a bug before also. I disabled the feature for now until a fix can be found.

2021-09-01 15:42 UTC, joykuotw approved these changes

2021-09-01 15:42 UTC, merged