Added mapbox_gl widget with updated build.gradle
Geovation/flutter_sandbox pull request #20
Opened 2021-03-11 13:43 UTC by mysticetii

It is for https://github.com/Geovation/flutter_sandbox/issues/5.
- Updated minSdkVersion to 20 as mapbox widget requires it.
- Added full page mapbox widget with full-screen map
- Access token is required and insert your token from mapbox into lib>mapbox>constants_mapbox.dart file in the ACCESS_TOKEN variable.

2021-03-11 23:47 UTC, joykuotw requested changes

2021-03-11 23:47 UTC, joykuotw commented on lib/main.dart
> +import 'mapbox/mapbox_page.dart';
Line 2 and 4 are doing the same import. Delete one of them.

2021-03-11 23:49 UTC, joykuotw commented
What version of iOS simulator and Android emulator do you use to run the app?

2021-03-12 06:39 UTC, mysticetii commented on lib/main.dart
> +import 'mapbox/mapbox_page.dart';
Done. I have just pushed another commit.

2021-03-12 06:42 UTC, mysticetii commented
I am developing this project using Android studio.
I do not have access to macOS therefore I am not using iOS simulator. For Android I am using emulator version: 30.4.5-7140946 and android version: 10.0 (Q) - API 29.

2021-03-12 11:19 UTC, joykuotw approved these changes

2021-03-12 11:22 UTC, merged