Add mb route
Geovation/flutter_sandbox pull request #24
Opened 2021-03-12 14:18 UTC by mysticetii

fixes #6 
- Added a custom route data in json
- Added route line representing the custom route

2021-03-12 16:48 UTC, joykuotw requested changes

2021-03-12 16:48 UTC, joykuotw commented on lib/main.dart
> +import 'mapbox/mapbox_page.dart';
duplicate

2021-03-12 18:19 UTC, joykuotw commented
Why are there many extra commits? don't forget to rebase the local working branch against the main first before making the pull request.

2021-03-13 04:17 UTC, closed without merging

2021-03-13 04:39 UTC, mysticetii commented on lib/main.dart
> +import 'mapbox/mapbox_page.dart';
fixed in https://github.com/Geovation/flutter_sandbox/pull/25