added firestore using a note taking demo
Geovation/flutter_sandbox pull request #54
Opened 2021-04-09 15:20 UTC by mysticetii

2021-04-10 17:18 UTC, joykuotw requested changes

2021-04-10 17:18 UTC, joykuotw commented on lib/firebase_firestore/firestore_page.dart
> +        });
you should handle if userData is null, or it will cause an exception.

2021-04-10 17:18 UTC, joykuotw commented on lib/firebase_firestore/firestore_page.dart
> +      rowWidget = (_auth.currentUser != null)
it would be better to always display the save button and indicate user to login to save note.

2021-04-12 07:09 UTC, mysticetii commented on lib/firebase_firestore/firestore_page.dart
> +        });
Thank you for pointing that out. I have added check in the next commit.

2021-04-12 07:10 UTC, mysticetii commented on lib/firebase_firestore/firestore_page.dart
> +      rowWidget = (_auth.currentUser != null)
Thank you for the suggestion. I will be modifying it in the next commit.

2021-04-12 10:39 UTC, mysticetii commented on lib/firebase_firestore/firestore_page.dart
> +      rowWidget = (_auth.currentUser != null)
The navigation has been updated.

2021-04-12 18:42 UTC, joykuotw requested changes
1. If you have already loggined and use side drawer to log out at Firestore page, the save button doesn't prompt to login when clicked at this point.
2. Need to handle empty email or password during login, or the app will crash.

2021-04-12 18:42 UTC, joykuotw commented on lib/firebase_firestore/firestore_page.dart
> +        _pageNavigator.setFromIndex = _pageNavigator.getCurrentPageIndex;
redundant, already set at line 48.

2021-04-13 06:14 UTC, mysticetii commented on lib/firebase_firestore/firestore_page.dart
> +        _pageNavigator.setFromIndex = _pageNavigator.getCurrentPageIndex;
Thank you for pointing that out. I have removed the redundant code

2021-04-13 06:15 UTC, mysticetii commented
I have added additional checks for the empty email + password field. Before the firebase auth was handling the null field. Updated the auth provider so that if users log out from the drawer window the save button in firestore demo will prompt for login again.

2021-04-14 00:40 UTC, joykuotw approved these changes

2021-04-14 00:44 UTC, merged

2021-04-14 00:45 UTC, joykuotw commented
It works but would be better to just use a listener to `authStateChanges()` in the Auth provider and update the user login status, so you don't need to use the `StreamBuilder` and can get the things you want from the provider instead.

Merge it and I will make the update later then.